# Generated by Django 4.1.7 on 2023-04-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(max_length=50)),
                ('nome_autor', models.CharField(max_length=50)),
            ],
        ),
    ]
